version: '3.8'

services:
  invext-api:
    build: .
    image: invext-api
    ports:
      - 8080:8080

  invext-postgres:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    volumes:
      - invext-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=invext
      - POSTGRES_USER=invext
      - POSTGRES_PASSWORD=invext

  invext-pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 3300:3300
    volumes:
      - invext-pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=fake@email.com
      - PGADMIN_DEFAULT_PASSWORD=123
      - PGADMIN_LISTEN_PORT=3300

volumes:
  invext-postgres:
    name: invext-postgres
  invext-pgadmin:
    name: invext-pgadmin
